[package]
name = "json_formatter"
version = "0.1.0"
publish = false
edition.workspace = true

[dependencies]
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
gpui.workspace = true
gpui-component = { workspace = true }

[lints]
workspace = true
